name: test_ci

on:
  pull_request:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Setup GraalVM Comunity Edition
        uses: rinx/setup-graalvm-cd@v0.0.5
        with:
          graalvm-version: "20.2.0"
          java-version: "java11"
          native-image: "true"
      
      - name: show java version
        run: java -version

      - name: mvn clean
        run: mvn clean

      - name: mvn package
        run: mvn package
